# Form implementation generated from reading ui file 'edit_subject.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditSubjectForm:
    def setupUi(self, EditSubjectForm):
        EditSubjectForm.setObjectName("EditSubjectForm")
        EditSubjectForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        EditSubjectForm.resize(444, 300)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditSubjectForm.sizePolicy().hasHeightForWidth())
        EditSubjectForm.setSizePolicy(sizePolicy)
        EditSubjectForm.setMaximumSize(QtCore.QSize(500, 300))
        self.gridLayout = QtWidgets.QGridLayout(EditSubjectForm)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 9, 10, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=EditSubjectForm)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2,
        )
        self.title_input = QtWidgets.QLineEdit(parent=EditSubjectForm)
        self.title_input.setObjectName("title_input")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.title_input,
        )
        self.label_3 = QtWidgets.QLabel(parent=EditSubjectForm)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3,
        )
        self.teacher_combo = QtWidgets.QComboBox(parent=EditSubjectForm)
        self.teacher_combo.setObjectName("teacher_combo")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.teacher_combo,
        )
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.main_label = QtWidgets.QLabel(parent=EditSubjectForm)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_label.sizePolicy().hasHeightForWidth())
        self.main_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.main_label.setFont(font)
        self.main_label.setIndent(-1)
        self.main_label.setObjectName("main_label")
        self.gridLayout.addWidget(self.main_label, 0, 0, 1, 1)
        self.submit_btn = QtWidgets.QPushButton(parent=EditSubjectForm)
        self.submit_btn.setObjectName("submit_btn")
        self.gridLayout.addWidget(self.submit_btn, 2, 0, 1, 1)

        self.retranslateUi(EditSubjectForm)
        QtCore.QMetaObject.connectSlotsByName(EditSubjectForm)

    def retranslateUi(self, EditSubjectForm):
        _translate = QtCore.QCoreApplication.translate
        EditSubjectForm.setWindowTitle(
            _translate("EditSubjectForm", "Редактирование предмета"),
        )
        self.label_2.setText(_translate("EditSubjectForm", "Название"))
        self.label_3.setText(_translate("EditSubjectForm", "Учитель"))
        self.main_label.setText(
            _translate("EditSubjectForm", "Редактирование предмета"),
        )
        self.submit_btn.setText(_translate("EditSubjectForm", "Сохранить"))
