# Form implementation generated from reading ui file 'hometask_list.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HometaskList(object):
    def setupUi(self, HometaskList):
        HometaskList.setObjectName("HometaskList")
        HometaskList.resize(580, 290)
        self.gridLayout = QtWidgets.QGridLayout(HometaskList)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=HometaskList)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.show_done = QtWidgets.QCheckBox(parent=HometaskList)
        self.show_done.setText("")
        self.show_done.setObjectName("show_done")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.show_done)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=HometaskList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.list_hometask = QtWidgets.QListWidget(parent=HometaskList)
        self.list_hometask.setSelectionRectVisible(False)
        self.list_hometask.setObjectName("list_hometask")
        self.gridLayout.addWidget(self.list_hometask, 2, 0, 1, 1)
        self.add_more = QtWidgets.QPushButton(parent=HometaskList)
        self.add_more.setObjectName("add_more")
        self.gridLayout.addWidget(self.add_more, 3, 0, 1, 1)

        self.retranslateUi(HometaskList)
        QtCore.QMetaObject.connectSlotsByName(HometaskList)

    def retranslateUi(self, HometaskList):
        _translate = QtCore.QCoreApplication.translate
        HometaskList.setWindowTitle(_translate("HometaskList", "Список ДЗ"))
        self.label_2.setText(_translate("HometaskList", "Показать выполненные"))
        self.label.setText(_translate("HometaskList", "Предстоящие задания"))
        self.list_hometask.setSortingEnabled(False)
        self.add_more.setText(_translate("HometaskList", "Добавить новые"))
