# Form implementation generated from reading ui file 'progress.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Progress(object):
    def setupUi(self, Progress):
        Progress.setObjectName("Progress")
        Progress.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Progress)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=Progress)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.show_without_mark = QtWidgets.QCheckBox(parent=Progress)
        self.show_without_mark.setText("")
        self.show_without_mark.setObjectName("show_without_mark")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.show_without_mark)
        self.label_3 = QtWidgets.QLabel(parent=Progress)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.sorting = QtWidgets.QComboBox(parent=Progress)
        self.sorting.setObjectName("sorting")
        self.sorting.addItem("")
        self.sorting.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sorting)
        self.refresh = QtWidgets.QPushButton(parent=Progress)
        self.refresh.setObjectName("refresh")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.refresh)
        self.gridLayout.addLayout(self.formLayout, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=Progress)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.table = QtWidgets.QTableWidget(parent=Progress)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.table, 3, 1, 1, 1)

        self.retranslateUi(Progress)
        QtCore.QMetaObject.connectSlotsByName(Progress)

    def retranslateUi(self, Progress):
        _translate = QtCore.QCoreApplication.translate
        Progress.setWindowTitle(_translate("Progress", "Моя успеваемость"))
        self.label_2.setText(_translate("Progress", "Без ср. балла"))
        self.label_3.setText(_translate("Progress", "Сортировать по"))
        self.sorting.setItemText(0, _translate("Progress", "Названию предмета"))
        self.sorting.setItemText(1, _translate("Progress", "Среднему баллу"))
        self.refresh.setText(_translate("Progress", "Обновить"))
        self.label.setText(_translate("Progress", "Моя успеваемость"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Progress", "Предмет"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Progress", "Средний балл"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Progress", "Оценки"))
