# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(500, 328)
        self.gridLayout_2 = QtWidgets.QGridLayout(Register)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(parent=Register)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(parent=Register)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=Register)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.name_input = QtWidgets.QLineEdit(parent=Register)
        self.name_input.setObjectName("name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_input)
        self.label_2 = QtWidgets.QLabel(parent=Register)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.age_input = QtWidgets.QSpinBox(parent=Register)
        self.age_input.setObjectName("age_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.age_input)
        self.label_3 = QtWidgets.QLabel(parent=Register)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.address_input = QtWidgets.QLineEdit(parent=Register)
        self.address_input.setObjectName("address_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.address_input)
        self.label_4 = QtWidgets.QLabel(parent=Register)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.timezone_input = QtWidgets.QSpinBox(parent=Register)
        self.timezone_input.setObjectName("timezone_input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.timezone_input)
        self.label_avatar = QtWidgets.QLabel(parent=Register)
        self.label_avatar.setObjectName("label_avatar")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_avatar)
        self.avatar_upload_btn = QtWidgets.QPushButton(parent=Register)
        self.avatar_upload_btn.setObjectName("avatar_upload_btn")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.avatar_upload_btn)
        self.submit_btn = QtWidgets.QPushButton(parent=Register)
        self.submit_btn.setObjectName("submit_btn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.submit_btn)
        self.gridLayout.addLayout(self.formLayout, 6, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Создание аккаунта"))
        self.label_6.setText(_translate("Register", "ДневникШкольника!"))
        self.label_5.setText(_translate("Register", "Добро пожаловать в приложение"))
        self.label.setText(_translate("Register", "Ваше имя"))
        self.label_2.setText(_translate("Register", "Ваш возраст"))
        self.label_3.setText(_translate("Register", "Ваш адрес"))
        self.label_4.setText(_translate("Register", "Часовой пояс относительно UTC"))
        self.label_avatar.setText(_translate("Register", "Загрузить аватар"))
        self.avatar_upload_btn.setText(_translate("Register", "Выбрать файл"))
        self.submit_btn.setText(_translate("Register", "Создать аккаунт"))
