# Form implementation generated from reading ui file '.\resources\forms\schedule.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Schedule(object):
    def setupUi(self, Schedule):
        Schedule.setObjectName("Schedule")
        Schedule.resize(646, 400)
        self.list_weeks = QtWidgets.QListWidget(parent=Schedule)
        self.list_weeks.setGeometry(QtCore.QRect(10, 80, 171, 311))
        self.list_weeks.setSelectionRectVisible(False)
        self.list_weeks.setObjectName("list_weeks")
        self.label = QtWidgets.QLabel(parent=Schedule)
        self.label.setGeometry(QtCore.QRect(10, 10, 631, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.refresh = QtWidgets.QPushButton(parent=Schedule)
        self.refresh.setGeometry(QtCore.QRect(190, 50, 451, 20))
        self.refresh.setObjectName("refresh")
        self.month_year_picker = QtWidgets.QPushButton(parent=Schedule)
        self.month_year_picker.setGeometry(QtCore.QRect(10, 50, 171, 23))
        self.month_year_picker.setObjectName("month_year_picker")
        self.days_table = QtWidgets.QTableView(parent=Schedule)
        self.days_table.setGeometry(QtCore.QRect(190, 80, 451, 311))
        self.days_table.setObjectName("days_table")

        self.retranslateUi(Schedule)
        QtCore.QMetaObject.connectSlotsByName(Schedule)

    def retranslateUi(self, Schedule):
        _translate = QtCore.QCoreApplication.translate
        Schedule.setWindowTitle(_translate("Schedule", "Form"))
        self.list_weeks.setSortingEnabled(False)
        self.label.setText(_translate("Schedule", "Просмотр расписания"))
        self.refresh.setText(_translate("Schedule", "Обновить"))
        self.month_year_picker.setText(_translate("Schedule", "Выбрать месяц и год"))
