# Form implementation generated from reading ui file 'subject_list.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SubjectList(object):
    def setupUi(self, SubjectList):
        SubjectList.setObjectName("SubjectList")
        SubjectList.resize(580, 290)
        self.gridLayout = QtWidgets.QGridLayout(SubjectList)
        self.gridLayout.setObjectName("gridLayout")
        self.list_subject = QtWidgets.QListWidget(parent=SubjectList)
        self.list_subject.setSelectionRectVisible(False)
        self.list_subject.setObjectName("list_subject")
        self.gridLayout.addWidget(self.list_subject, 2, 0, 1, 1)
        self.add_more = QtWidgets.QPushButton(parent=SubjectList)
        self.add_more.setObjectName("add_more")
        self.gridLayout.addWidget(self.add_more, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=SubjectList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.refresh = QtWidgets.QPushButton(parent=SubjectList)
        self.refresh.setObjectName("refresh")
        self.gridLayout.addWidget(self.refresh, 1, 0, 1, 1)

        self.retranslateUi(SubjectList)
        QtCore.QMetaObject.connectSlotsByName(SubjectList)

    def retranslateUi(self, SubjectList):
        _translate = QtCore.QCoreApplication.translate
        SubjectList.setWindowTitle(_translate("SubjectList", "Список предметов"))
        self.list_subject.setSortingEnabled(False)
        self.add_more.setText(_translate("SubjectList", "Добавить новые"))
        self.label.setText(_translate("SubjectList", "Список предметов"))
        self.refresh.setText(_translate("SubjectList", "Обновить"))
