# Form implementation generated from reading ui file 'teacher_list.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TeacherList(object):
    def setupUi(self, TeacherList):
        TeacherList.setObjectName("TeacherList")
        TeacherList.resize(580, 290)
        self.gridLayout = QtWidgets.QGridLayout(TeacherList)
        self.gridLayout.setObjectName("gridLayout")
        self.list_teacher = QtWidgets.QListWidget(parent=TeacherList)
        self.list_teacher.setSelectionRectVisible(False)
        self.list_teacher.setObjectName("list_teacher")
        self.gridLayout.addWidget(self.list_teacher, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=TeacherList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.add_more = QtWidgets.QPushButton(parent=TeacherList)
        self.add_more.setObjectName("add_more")
        self.gridLayout.addWidget(self.add_more, 2, 0, 1, 1)

        self.retranslateUi(TeacherList)
        QtCore.QMetaObject.connectSlotsByName(TeacherList)

    def retranslateUi(self, TeacherList):
        _translate = QtCore.QCoreApplication.translate
        TeacherList.setWindowTitle(_translate("TeacherList", "Список учителей"))
        self.list_teacher.setSortingEnabled(False)
        self.label.setText(_translate("TeacherList", "Список учителей"))
        self.add_more.setText(_translate("TeacherList", "Добавить новых"))
