"""init.

Revision ID: 55cf069466d5
Revises: c76289a88178
Create Date: 2025-09-08 12:49:28.541534

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55cf069466d5"
down_revision: str | Sequence[str] | None = "c76289a88178"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Teacher",
        sa.Column("teacher_id", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("avatar", sa.Text(), nullable=True),
        sa.Column("student_id", sa.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("teacher_id"),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["Student.student_id"],
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("teacher_id"),
    )

    op.create_table(
        "Student",
        sa.Column("student_id", sa.Text(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("avatar", sa.Text(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("home_address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("student_id"),
        sa.UniqueConstraint("student_id"),
    )

    op.create_table(
        "Subject",
        sa.Column("subject_id", sa.Text(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("teacher_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["Teacher.teacher_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["Student.student_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("subject_id"),
        sa.UniqueConstraint("subject_id"),
    )

    op.create_table(
        "Lesson",
        sa.Column("lesson_id", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("mark", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("room", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["Subject.subject_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["Student.student_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("lesson_id"),
        sa.UniqueConstraint("lesson_id"),
    )

    op.create_table(
        "Hometask",
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False, server_default="0"),
        sa.Column("lesson_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["Lesson.lesson_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["Student.student_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("task_id"),
        sa.UniqueConstraint("task_id"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Hometask")
    op.drop_table("Lesson")
    op.drop_table("Subject")
    op.drop_table("Student")
    op.drop_table("Teacher")
    # ### end Alembic commands ###
